trigger: none

pool:
  name: ADO19JULY

steps:
  - script: |
      java --version
      mvn --version
    displayName: "Check Java and Maven Versions"
  - task: Maven@4
    inputs:
      mavenPomFile: 'pom.xml'
      goals: 'mvn clean deploy'
      options: '-s .mvn/setting.xml'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      javaHomeOption: 'JDKVersion'
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      effectivePomSkip: false
      sonarQubeRunAnalysis: false

